// Real footage for the deterministic timeline: cut a clip out of a video into a JPEG sequence the page can show
// frame-exactly (window.seek awaits image decode). Registers the clip in assets/footage/footage.js.
//   node frames.mjs <src.mp4> --cuts [--crop w:h:x:y]          # list shot changes to choose in/out points
//   node frames.mjs <src.mp4> <id> --ss 3.2 --t 4 [--crop w:h:x:y] [--w 960] [--fps 30] [--q 3] [--vf "eq=saturation=1.1"]
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { spawnSync } from 'child_process';
import { argv } from './tools.mjs';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const [src, id] = process.argv.slice(2);
if (!src) { console.error('usage: node frames.mjs <src> <id> --ss s --t s [--crop w:h:x:y] [--w px] [--fps n]'); process.exit(1); }
const crop = argv('--crop');

if (process.argv.includes('--cuts')) {
  const vf = [crop && `crop=${crop}`, "select='gt(scene,0.28)'", 'showinfo'].filter(Boolean).join(',');
  const r = spawnSync('ffmpeg', ['-hide_banner', '-i', src, '-vf', vf, '-f', 'null', '-'], { encoding: 'utf8' });
  const cuts = [...r.stderr.matchAll(/pts_time:([\d.]+)/g)].map(m => (+m[1]).toFixed(2));
  const d = /Duration: (\d+):(\d+):([\d.]+)/.exec(r.stderr);
  console.log(`duration ${d ? (+d[1] * 3600 + +d[2] * 60 + +d[3]).toFixed(2) : '?'} s | shot changes: ${cuts.join(' ') || 'none'}`);
  process.exit(0);
}

const fps = Number(argv('--fps', 30)), w = Number(argv('--w', 0)), q = argv('--q', '3');
const dir = path.join(ROOT, 'assets', 'footage', id);
fs.rmSync(dir, { recursive: true, force: true }); fs.mkdirSync(dir, { recursive: true });
const vf = [crop && `crop=${crop}`, w && `scale=${w}:-2:flags=lanczos`, `fps=${fps}`, argv('--vf')].filter(Boolean).join(',');
const args = ['-v', 'error', '-y', ...(argv('--ss') ? ['-ss', argv('--ss')] : []), '-i', src, ...(argv('--t') ? ['-t', argv('--t')] : []), '-vf', vf, '-q:v', q, path.join(dir, '%04d.jpg')];
const r = spawnSync('ffmpeg', args, { encoding: 'utf8' });
if (r.status) { console.error(r.stderr); process.exit(1); }
const files = fs.readdirSync(dir).filter(f => f.endsWith('.jpg')).sort();
const probe = spawnSync('ffprobe', ['-v', 'error', '-show_entries', 'stream=width,height', '-of', 'csv=p=0', path.join(dir, files[0])], { encoding: 'utf8' }).stdout.trim().split(',').map(Number);

const man = path.join(ROOT, 'assets', 'footage', 'footage.js');
let M = {};
if (fs.existsSync(man)) { const m = /var FOOTAGE = (\{[\s\S]*?\});\n/.exec(fs.readFileSync(man, 'utf8')); if (m) M = JSON.parse(m[1]); }
M[id] = { dir: `../assets/footage/${id}`, fps, count: files.length, w: probe[0], h: probe[1], src: path.basename(src), ss: +(argv('--ss') || 0), crop: crop || null };
fs.writeFileSync(man, `// generated by frames.mjs: JPEG sequences shown by footage() in video/main.js\nvar FOOTAGE = ${JSON.stringify(M, null, 1)};\nif (typeof module !== 'undefined') module.exports = FOOTAGE;\n`);
const bytes = files.reduce((s, f) => s + fs.statSync(path.join(dir, f)).size, 0);
console.log(`${id}: ${files.length} frames ${probe.join('x')} @${fps}fps (${(files.length / fps).toFixed(2)} s, ${(bytes / 1e6).toFixed(1)} MB) -> assets/footage/${id}`);
