// Place every verified phrase at its cue (video/cues.js -> CUES.vo = { v01: seconds, ... }) on a 48 kHz stereo
// track with a light broadcast chain, and export the absolute onset of every displayed word for on-screen sync.
//   node narration/assemble.mjs            -> out/vo.wav + video/vo_words.js (VO_WORDS.v01 = [t0, t1, ...])
//   node narration/assemble.mjs --suggest  -> prints a cue layout from the phrase durations (paste into cues.js)
import fs from 'fs';
import path from 'path';
import { spawnSync } from 'child_process';
import { VO, DIR, ROOT, cues } from './common.mjs';

const P = JSON.parse(fs.readFileSync(path.join(DIR, 'phrases.json'), 'utf8')).phrases;
const ids = VO.groups.flatMap(g => g.lines.map(l => l.id));

if (process.argv.includes('--suggest')) {
  // lines of one group follow each other closely; a new group (scene) leaves room for the cut/transition
  const start = Number(process.argv[process.argv.indexOf('--suggest') + 1]) || 0.5;
  let t = start; const out = {};
  VO.groups.forEach((g, gi) => g.lines.forEach((l, li) => {
    if (gi && !li) t += VO.sceneGap ?? 0.9; else if (li) t += VO.lineGap ?? 0.3;
    out[l.id] = +t.toFixed(2); t += P[l.id].dur;
  }));
  console.log(`vo: ${JSON.stringify(out).replace(/"/g, '').replace(/,/g, ', ')},  // speech ends ${t.toFixed(2)} s`);
  process.exit(0);
}

const C = cues();
if (!C?.vo) { console.error('video/cues.js needs CUES.vo (run with --suggest for a starting layout)'); process.exit(1); }
const dur = C.duration, inputs = [], parts = [];
ids.forEach((id, i) => {
  const p = P[id]; if (!p) throw new Error('missing phrase ' + id + ' (run produce.mjs)');
  if (C.vo[id] == null) throw new Error('missing cue CUES.vo.' + id);
  const next = ids[i + 1] != null ? C.vo[ids[i + 1]] : dur;
  if (C.vo[id] + p.dur > next - 0.05) console.warn(`  ! ${id} runs ${(C.vo[id] + p.dur - next + 0.05).toFixed(2)} s into the next cue`);
  inputs.push('-i', path.join(ROOT, p.file));
  parts.push(`[${i}:a]aresample=48000,adelay=${Math.round(C.vo[id] * 1000)}:all=1[v${i}]`);
});
const chain = VO.chain || 'highpass=f=80,equalizer=f=250:t=q:w=1.2:g=-2,equalizer=f=3500:t=q:w=1.4:g=2.5,equalizer=f=10000:t=h:w=0.7:g=1.5,acompressor=threshold=-20dB:ratio=3:attack=5:release=110:makeup=3dB,alimiter=limit=0.89';
const fc = parts.join(';') + ';' + ids.map((_, i) => `[v${i}]`).join('') + `amix=inputs=${ids.length}:normalize=0,apad=whole_dur=${dur},atrim=0:${dur},${chain},pan=stereo|c0=c0|c1=c0[vo]`;
fs.mkdirSync(path.join(ROOT, 'out'), { recursive: true });
const r = spawnSync('ffmpeg', ['-v', 'error', '-y', ...inputs, '-filter_complex', fc, '-map', '[vo]', '-ar', '48000', '-c:a', 'pcm_s16le', path.join(ROOT, 'out', 'vo.wav')], { encoding: 'utf8' });
if (r.status) { console.error(r.stderr); process.exit(1); }

const words = Object.fromEntries(ids.map(id => [id, P[id].words.map(w => +(C.vo[id] + w.s).toFixed(3))]));
fs.writeFileSync(path.join(ROOT, 'video', 'vo_words.js'), `// generated by narration/assemble.mjs: absolute onset (s) of every displayed word of each VO line\nvar VO_WORDS = ${JSON.stringify(words)};\nif (typeof module !== 'undefined') module.exports = VO_WORDS;\n`);
ids.forEach(id => console.log(`  ${id} ${C.vo[id].toFixed(2)} → ${(C.vo[id] + P[id].dur).toFixed(2)}  ${P[id].text}`));
console.log('vo -> out/vo.wav | word onsets -> video/vo_words.js');
